### ISSUE TITLE
Make version number obtainable within C++

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#140]
The BuDDy package has functions within C++ to obtain the library version.

[One can place CMake variables inside of the source code](https://cmake.org/pipermail/cmake/2013-June/054983.html) such that we can merely place define and bump the project version inside of CMake, and then C++ follows along nicely. [Here](https://riptutorial.com/cmake/example/32603/using-cmake-to-define-the-version-number-for-cplusplus-usage) is another source of how to do so. Most reasonable place to put it would be `adiar/adiar.h.in` or in a new file `adiar/version.h.in`.

**Comment by svenkat19** [comment]
Hey, I would like to help. I am new to this, so can you please guide me?

**Comment by SSoelvsten** [comment]
I am willing to answer specific questions if you have any. Is the description above too vague, do you have a hard time getting your local fork of the repository up and going? The use of _.in_ files I have no experience with, but a quick Google can probably answer your questions.
