### ISSUE TITLE
Pop ingoing arcs before pushing new recursion requests

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#150]
Some of the worst-case bounds in #98 have a _+2_ which could be removed by popping all ingoing arcs from the priority queue before pushing the new recursion requests for the children. 

Yet, removing the _+2_ is not really worth making the algorithms more incomprehensible; they already are hard to get your head around as of now. So, if this makes the code much worse, then one may want to just ignore it.

- [x] *bdd/if_then_else.cpp*
- [x] *internal/intercut.h*
- [x] *internal/product_construction.h*
- [x] *internal/quantify.h*
- [x] *internal/substitute.h*

**Comment by AnnaBlume99** [comment]
Hvordan kan man se hvilke arcs der er rigtige at poppe? Er det dem der har den nuværende source som target? Eller betyder "ingoing arcs" noget andet?

**Comment by SSoelvsten** [comment]
Hver algoritme håndterer en knude i to faser: 
1. Indsætter udgående kanter til børnene ind i prioritetskøen (non-sink) eller outputtet (sinks)
2. Henter alle indgående kanter fra prioritetskøen og udskriver dem i outputtet

Her vil vi gerne bytte om på rækkefølgen, således det er (2) og så (1).
