### ISSUE TITLE
Make data.h header-only

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#163]
The computations in _data.h_ are used in a lot of places very often. These functions are extremely small, and so the function call itself cost just as much (if not more) than the actual computations. So, we want to force them to be _inlined_. To do this, we need to move the implementation in _data.cpp_ into _data.h_ and have every function be preceded by the _inline_ keyword.

- [ ] All `const` values should be moved over as a `constexpr`, including the variables only in *data.cpp*
- [ ] For each function declaration (a) precede it with an `inline` and (b) the replace the `;` with the `{ ... }` part of its implementation.

**Comment by AnnaBlume99** [comment]
Skal jeg flytte alting fra data.cpp over i data.h eller kun de ting der i forvejen findes i data.h? 
Altså, skal jeg kunne slette data.cpp når jeg er færdig?

**Comment by SSoelvsten** [comment]
Ideally everything is moved and *data.cpp* is deleted. I'm not sure whether the lambda functions for the *bool_op* can be moved, so they may possibly have to stay as is.

**Comment by SSoelvsten** [comment]
Correction: Yes one can make lambdas into a `constexpr`.
https://docs.microsoft.com/en-us/cpp/cpp/lambda-expressions-constexpr
