### ISSUE TITLE
Switch to internal memory levelized priority queue in Reduce based on 1-level cut

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#168]
In #98 we template the *levelized priority queue* to switch to an internal memory variant to improve all the top-down algorithms by finding an approximate upper bound. For *Reduce* we can instead find the exact value! To this end, we need to look at *i*-level cuts.

> *Definition*: An _i_-level cut of a BDD for _f_ is a cut (S,T) of its DAG _G<sub>f</sub>_, where there exists some _j_ such that nodes in _S_ have a label _l < j+i_ and nodes in _T_ have a label _l > j_.

Specifically, a 1-level cut between level _i_ and _i+1_ is the total number of edges _e_ with the label of their source being _i_ or lower and their target being _i+1_ or higher.

## Computing the 1-level cuts of unreduced graphs

A one-level cut (of internal arcs) is the size of the priority queue in the preceding top-down algorithm after processing level _i_ and before processing _i+1_. With a single variable one can maintain this value in O(L) time. Before returning, this value can be stored within the `arc_file` for the Reduce to consume.

- [x] Extend *arc_file* with `max_1level_cut`.

**Algorithms to include 1-level cut**

- [x] *bdd/if_then_else.h*
- [x] *internal/intercut.h*
- [x] *internal/product_construction.h*
- [x] *internal/quantify.h*
- [x] *internal/substitution.h*
- [x] *internal/build.h*

## Using the 1-level cuts

Notice, that the priority queue of _Reduce_ always have arcs from level _i_ and to some level _j < i_, and every arc is an arc from the input with its target re-routed to some node in the output. So the priority queue is always a 1-level cut of the input DAG (**without any sink arcs). So, the maximal 1-level cut on the input DAG is the **exact** maximum size of the priority queue!

- [x] Add *internal/priority_queue.h* with both an `internal_priority_queue` and an `external_priority_queue`.
- [x] Extend the *internal/levelized_priority_queue.h* with `max_size` as an extra argument (dummy value max)
- [x] Extend the *internal/levelized_priority_queue.h* with having `sorter_t` and `pq_t` as template arguments.
- [x] Use the cut as the *max_size* in *internal/reduce.h*

**NOTE:** We can solve this before #98 and merely add the templated *levelized priority queue* here instead.

**Comment by TAH125** [comment]
iuj2045!@@320

**Comment by TAH125** [comment]
state,      // same as `store.state`, or local state if in modules
  rootState,  // same as `store.state`, only in modules
  commit,     // same as `store.commit`
  dispatch,   // same as `store.dispatch`
  getters,    // same as `store.getters`, or local getters if in modules
  rootGetters // same as `store.getters`, only in modules
}

**Comment by SSoelvsten** [comment]
@TAH125 I don't understand your comment. You seem to have written down some notes on [Vue.js](https://vuejs.org/) whereas this is a C++ project.
