### ISSUE TITLE
Replace tpie::internal_priority_queue with a sequence heap

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#172]
With #98 we replace the external memory `tpie::priority_queue` with the `tpie::internal_priority_queue` whenever we can guarantee it can fit into main memory. The `tpie::internal_priority_queue` is a binary heap using the algorithms in the standard C++ library.

Right now, for the 8-queens problem the `tpie::internal_priority_queue` is only 10% of all computation time, so changing to another type of heap does not do much compared to the 28% spent on sorting. Yet, there are two alternatives to a binary heap that are faster for large enough instances: a *d-ary Heap* where *d* is based on a block size and a *Sequence Heap*. I'd favour the *sequence heap*.

## 'Block Size' based on cache line.

To this end, we need to derive a good 'block size' for the cache-to-cache and cache-to-RAM levels of the memory hierarchy. Here, the actual size of the cache line is a reasonable base point. For most modern machines the cache-line (on all levels) is exactly 64-bytes. In our cases a node is 24 bytes, an arc is 16 bytes, etc. so with 1, 2, or 3 cache lines we can make everything cache-aligned.

The fan-out of every node is
```
  d = lcm(cache_line_size, size_of(T))/size_of(T)
```
To derive this alignment, one may be interested in the following features of C++

- [alignas](https://en.cppreference.com/w/cpp/language/alignas), [aligned storage](https://en.cppreference.com/w/cpp/types/aligned_storage) may be of interest to have better control over the cache-line. This [description by Microsoft](https://docs.microsoft.com/en-us/cpp/cpp/align-cpp?view=msvc-170) may be of help and.
- This [cache-aligned queue](https://stackoverflow.com/questions/8469427/how-and-when-to-align-to-cache-line-size) can partly be used as inspiration. Furthermore, this [memory alignment wrapper](https://github.com/NickStrupat/Aligned) is also a great source of inspiration.
- [Here](https://stackoverflow.com/a/7284876) is a nice way to pass the cache-line size in the _makefile_ into CMake.

## Sequence Heap

Gerth Stølthing Brodal made me aware of [this paper](https://dl.acm.org/doi/pdf/10.1145/351827.384249) by Peter Sanders, where he applies I/O techniques to improve cache performance. The resulting data structure is called a _sequence heap_. The source code used for that paper can be found [here](https://algo2.iti.kit.edu/sanders/programs/spq/) (none of it may be reused since its license is for "only educational and non-commercial use").

From their experiments it seems that the sequence heap outperforms the binary heap and d-ary heap when one goes outside of the L1 cache. Inside of the L1 cache the binary heap wins, but it is only a 15% performance decrease in using the sequence heap within L1 cache. On the other hand, there is a 2x - 3x performance increase in L2 and beyond.

- [ ] Add `tpie::internal_sequence_heap` (name pending) directly inside of TPIE. Create a pull request for it to the main repo such that everyone can benefit from this (and more people have had an eye on it).
  - Some of the ideas for the _d_-ary heap above can be reused to derive the block size and the fanout.
- [ ] Change the priority queue inside of the `tpie::internal_priority_queue` to use the new Sequence Heap instead.

**Comment by SSoelvsten** [comment]
@Mortal , @antialize , or @thomasmoelhave would you be interested in us adding this directly to TPIE instead?

**Comment by SSoelvsten** [comment]
Gerth Stølthing Brodal made me aware of [this paper](https://dl.acm.org/doi/pdf/10.1145/351827.384249) by Peter Sanders, where they apply the I/O-efficiency technique to improve cache performance. For about 1024 elements (of type _int_, i.e. 4 KiB) or more the queue by Sander's outperforms a binary heap and the above d-ary heap. The performance difference for even fewer elements may not be worth using a binary heap too.

**Comment by Mortal** [comment]
As you might know, Sanders' "fast priority queues for cached memory" is already the basis for the [external memory priority queue in TPIE](https://github.com/thomasmoelhave/tpie/blob/master/tpie/priority_queue.h#L54). I didn't know that Sanders' source was actually available on the internet like that!

It seems within scope for TPIE to have an internal memory implementation of Sanders' PQ, so we could look into adding that if you have a suitably general implementation. I think I would add it as a separate type in TPIE (instead of letting it replace the current internal_priority_queue implementation), but let me know what you think.

**Comment by SSoelvsten** [comment]
I remember that the priority queue was based off of some of Sanders' work, but I did not know that it was this exact one. If TPIE already includes this, then I assume using the deep machinery of TPIE would make implementation much easier.

And adding it under a separate name seems like a good idea. :)

**Comment by SSoelvsten** [comment]
Just to clarify, while the source code of Sanders' is available it is put under a "only educational and non-commercial use" license, so none of it may be reused.

**Comment by SSoelvsten** [comment]
With #149, we switched to a non-bucketed priority queue when below a given threshold. Yet, this threshold is so small, that the entire thing can easily be within L1 cache, where the binary heap is the best solution.

For larger instances, the buckets are primarily used, and so the overflow queue never grows very large, i.e. it can probably still fit in L1 cache. Hence, we probably will not gain much from this.

**Comment by SSoelvsten** [comment]
While looking for an answer to a question from a student, I found this generalised *D*-ary heap template 

https://github.com/valyala/gheap

**Comment by SSoelvsten** [comment]
The following CMake code stores the page size in a variable. One can extend it to use the `getconf LEVEL1_DCACHE_LINESIZE` command instead.
```cmake
if (UNIX)
  execute_process(COMMAND "getconf" "PAGESIZE"
    RESULT_VARIABLE UNIX_PS_CODE
    OUTPUT_VARIABLE UNIX_PS_STDOUT)
  if (UNIX_PS_CODE EQUAL 0)
    set (PAGE_SIZE "${UNIX_PS_STDOUT}")
  endif ()
endif (UNIX)
if (NOT DEFINED PAGE_SIZE)
  set (PAGE_SIZE "4096")
endif()
```
