### ISSUE TITLE
Add warning when calling `adiar_stats` without `ADIAR_STATS`

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#242]
Similar to `adiar_printstat` we should print to `std::cerr` if one tries to call `adiar_stats` while not having the `ADIAR_STATS` CMake variable set to *ON*.

**Comment by AnnaBlume99** [comment]
Hvilken fil skal jeg bruge her?

**Comment by SSoelvsten** [comment]
I *adiar/statistics.cpp* har vi implementationen af de statistik relaterede funktioner. I `adiar_printstat` funktionen har du et eksempel på, hvordan koden ændres baseret på compiler flagene. Så, jeg tænkte noget i retning af
```cpp
#ifndef ADIAR_STATS
  std::cerr << "<text here....>"
#endif
```
