### ISSUE TITLE
Max 1 and 2-level cut approximation for zipping (if_then_else)

### ISSUE THREAD

**Issue by AnnaBlume99** [SSoelvsten/adiar#272]
In *bdd/if_then_else.cpp* the helper function `ite_zip_bdds` does not set the `max_ilevel_cut` for the returned bdd.
This can be over-approximated for a given *cut_type* *ct* as follows

> `std::max(bdd_if.max_ilevel_cut[cut_type::ALL], bdd_then.max_ilevel_cut[ct] + bdd_else.max_ilevel_cut[ct])`.

But, there is currently no way to get the max_1level_cut directly from a bdd (will be possible after #280 is complete).

The cuts also need to be added to the tests for zipping (with GreaterThanOrEqual, since we are over-approximating)

**Comment by SSoelvsten** [comment]
For the 2-level cut, we want to do the same, but we should always use the *all sinks* version for the conditional *if* BDD.

**Comment by SSoelvsten** [comment]
Is now possible with #318 .
