### ISSUE TITLE
Reduce does not collect statistics

### ISSUE THREAD

**Issue by AnnaBlume99** [SSoelvsten/adiar#301]
When running tests (and main) all statistics gathered in reduce.h end up being 0.

**Comment by SSoelvsten** [comment]
Interestingly enough, it seems to work fine from the *bdd-benchmark* repo.

**Comment by SSoelvsten** [comment]
It seems as if *reduce.h* is for *test* compiled without the pre-processor having *ADIAR_STATS* and *ADIAR_STATS_EXTRA* defined.
