### ISSUE TITLE
Add `bdd_then`/`bdd_else`

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/adiar#557]
In the same vein as #553 , we may as well add aliases for the `bdd_restrict` and `zdd_onset`/`zdd_offset` functions (with a warning/remark in the documentation that they use linear time and should not be used to traverse the diagram).

- [x] Add `bdd_then` and `bdd_else` as an alias for `bdd_restrict(...)` with `bdd_minvar(...)` set respectively to *true* and *false*.
- [x] Add `zdd_onset(A)` and `zdd_offset(A)`, i.e. add an overload where *vars* is set to be *{zdd_minvar(A)}*.

All of the above should include a few unit tests to ensure they behave as expected.

**Additional context**
Requested on email by Anna Blume Jakobsen, based on what she needed in her prior BSc/MSc projects and student programmer tasks.

**Comment by Salonikansal2** [comment]
please assign , i am starting to work on this

**Comment by SSoelvsten** [comment]
In BuDDy, these are called `bdd_high` and `bdd_low`. Furthermore, `bdd_minvar` is also just called `bdd_var`.
