### ISSUE TITLE
Dot files for better images

### ISSUE THREAD

**Issue by gimmelemons** [SSoelvsten/adiar#602]
Hi,

![f](https://github.com/SSoelvsten/adiar/assets/65401076/46f24957-afd6-4c14-b1b7-5a0da0c2e299)

Is it possible to remove the id's when printing the dots? I just want the variable name.

Nice Project btw.

**Comment by SSoelvsten** [comment]
Hi,

Sorry I first see this now - I have somehow set up my email notifications for this repo incorrectly. Yes, this should be easy to fix; I'll look at it tomorrow.

**Comment by SSoelvsten** [comment]
I have added an optional last argument `include_id` (type *bool*) which by default is `false`. That is, `bdd_printdot(f, ..., false)`/`bdd_printdot(f, ...)` render a result as follows

![dot_test_bdd dot](https://github.com/SSoelvsten/adiar/assets/14313096/d7efd319-27bd-4af1-9e11-56a7bdbd4957)

As you can see, I also made the internal nodes round; this way it follows the conventional depiction of BDDs

Using `bdd_printdot(f, ..., true)` behaves as before (for development debugging purposes). But, I removed the *id* in the print, to better align the output with the paper(s).

![dot_test_bdd__with_ids dot](https://github.com/SSoelvsten/adiar/assets/14313096/90e08428-af1c-481f-bf85-b8b7eccc0c91)
